services:
    _defaults:
        autowire: true
        autoconfigure: true

    anonlytics.response_subscriber:
        class: DeFixIT\AnonlyticsBundle\EventListener\RequestSubscriber
        arguments:
            $parameterBag: "@parameter_bag"
        tags:
            - { name: kernel.event_subscriber }